# Generated by Django 5.0.3 on 2024-03-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_place_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestroomDetail',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.detail')),
                ('hasPaper', models.BooleanField()),
            ],
            bases=('core.detail',),
        ),
        migrations.CreateModel(
            name='StudyroomDetail',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.detail')),
                ('hasBed', models.BooleanField(default=True)),
            ],
            bases=('core.detail',),
        ),
        migrations.CreateModel(
            name='VendingMachineDetail',
            fields=[
                ('detail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.detail')),
                ('isFunctional', models.BooleanField()),
            ],
            bases=('core.detail',),
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='place',
            name='icon',
            field=models.ImageField(upload_to='images'),
        ),
    ]
