# Generated by Django 5.0.3 on 2024-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restroomdetail_studyroomdetail_vendingmachinedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(default='Vending Machine', max_length=100),
            preserve_default=False,
        ),
    ]
